export let englishContent = [
	"Introduce",
	"Works",
	"Testimonials",
	"Services",
	"Contact",
	"Blog",
	"Empower Your Digital Journey with Custom Web Solutions",
	"Dive into the world of digital innovation where creativity meets functionality. As a fullStack web developer skilled in WordPress, CSS, JavaScript, and more, I specialize in crafting custom ceb solutions. Let's collaborate and enhance your digital presence together.",
	"WORK WITH ME !",
	"Frontend | Web Design",
	"I specialize in creating captivating user interfaces through expert use of either HTML, CSS, JavaScript, Bootstrap and Sass, or of course Elementor the famous builder of WordPress, delivering seamless and engaging website experiences.",
	"Backend",
	"With expertise in server-side scripting and database management, I architect robust backend systems that power websites with efficiency and reliability using PHP and MySQL. Additionally, I use plugins like ACF, WooCommerce, Dokan, and more to enhance functionality and user experience.",
	"WordPress",
	"I leverage the flexibility of WordPress to craft dynamic websites with custom themes and plugins, marrying design with functionality for a seamless user experience.",
	"SEO",
	"My SEO proficiency ensures your website not only looks great but also ranks well, driving targeted organic traffic through strategic optimization techniques and identifying 'high-intent' keywords that are most effective for your customers",
	"Introduce",
	"Hello! I'm Abdelkarim Achlaih",
	"Every great development begins with a clear vision, meticulous planning, and a commitment to turning ideas into elegant, functional solutions.",
	"My two years of experience as a full stack web developer empower me to craft tailored solutions that speak to your unique project requirements.",
	"Technologies I Use",
	"Discover the cutting-edge technologies fueling my journey towards digital excellence",
	"Latest Works",
	"Perfect solutions for digital experience",
	"ALL",
	"Projects",
	"Stores",
	"Real Estate",
	"Templates",

	"All projects",
	"* Browse other projects on ",
	"my GitHub",
	"Project description",
	"Live Demo",
	"View Code",
	"Project Process",
	"Embark on a journey of collaboration as I'm guiding you through my project process. From inception to delivery, I follow a strategic path to ensure your vision comes to life",
	"I kickstart the process by diving deep into your ideas, exploring possibilities, and laying the foundation for your project's success.",
	"Copywriting",
	"Copywriting",
	"With focus on storytelling, engagement, and SEO optimization, I craft compelling content that resonates with your audience, enhances your brand narrative, and boosts your online visibility.",
	"Design",
	"Design",
	"I ensure that the visual elements I design perfectly complement the copywriting, creating a captivating user experience.",
	"Development",
	"Development",
	"Using above technologies and industry best practices, I bring your design concepts to life, meticulously crafting fully functional, feature-rich websites.",
	"Delivery",
	"Delivery",
	"Your satisfaction is my priority. I deliver the initial product and work closely with you to refine and enhance it based on your valuable feedback.",
	"Developed with",
	"Performance",
	"Experience blazing-fast performance with websites crafted for speed and efficiency. My commitment to excellence extends to optimizing every aspect of your website, ensuring lightning-fast loading times and a seamless user experience",

	"Testimonials",
	"What's my clients, friends say about me",
	"We would like to express our heartfelt gratitude for your outstanding work in developing our official website at <a target='_blank' href='https://staraimmo.ma/'>STARAIMMO</a>. Your dedication and expertise in creating our digital presence have greatly contributed to enhancing our online reach and showcasing our services effectively.",
	"One of the most impressive aspects of Abdelkarim's work is his commitment to creating solutions that are both aesthetically pleasing and highly functional.",

	"Engineer, Friend",
	"My Services",
	"Empowering your digital journey with innovative solutions that leave a lasting impression",
	"Search Engine Optimization (SEO)",
	"Ignite your online presence with a tailored SEO strategy that enhances your website's visibility on search engines, driving organic traffic and boosting rankings. Let's collaborate to maximize your impact in the digital landscape.",
	"Order Now",
	"Websites for businesses",
	"Transform your business into a digital success story with captivating websites designed to captivate your audience and drive leads. Let's demystify complex concepts and align your website with your marketing strategy for optimal results.",
	"Order Now",
	"E-Commerce Solutions",
	"Elevate your online store into a captivating shopping destination that converts browsers into buyers. Collaborate with me to optimize every aspect of your e-commerce store for success and customer retention.",
	"Order Now",
	"Custom Websites for Students, Bloggers, and Artists",
	"Empower your creative journey with personalized websites designed to showcase your talents and aspirations. Let's collaborate to transform your digital presence into a captivating canvas that resonates with your audience.",
	"Order Now",
	"PSD or Figma to Web Page or WordPress Theme",
	"Bring your design concepts to life with precision and elegance. Let's turn your creative designs into interactive digital masterpieces that captivate your audience.",
	"Order Now",
	"Web Application Development",
	"Streamline your business processes and enhance user experiences with custom web applications tailored to your specific needs. Let's revolutionize the way you do business online with intuitive solutions that drive growth and innovation.",
	"Order Now",

	"Let's make something amazing together.",
	"Start by saying hi",
	"Name",
	"Email",
	"Message",
	"© 2024, All Rights Reserved",
	"Design inspired from  <a href='https://dribbble.com/shots/11276631-DS-Personal-Developer-Portfolio'>Logan Cee</a>",
	"",
	"",
	"",
	"",
];
export let frenchContent = [
	"Introduire",
	"Travaux",
	"Témoignages",
	"Services",
	"Contact",
	"Blog",
	"Renforcez Votre Présence digitale avec des Solutions Web Sur-Mesure",
	"Explorez le monde de l'innovation digitale où la créativité fusionne avec la fonctionnalité. En tant que développeur web FullStack expert en WordPress, CSS, JavaScript et bien plus, je me consacre à concevoir des solutions web sur mesure. Travaillons ensemble pour enrichir votre empreinte digitale.",
	"TRAVAILLEZ AVEC MOI !",
	"Frontend | Web Design",
	"Je me spécialise dans la création d'interfaces utilisateur captivantes en utilisant de manière experte HTML, CSS, JavaScript, Bootstrap et Sass, ou bien évidemment Elementor, le célèbre plugin de WordPress, afin d'offrir des expériences web fluides et attrayantes.",
	"Backend",
	"Avec une expertise en script côté serveur et gestion de base de données, j'architecture avec PHP et MySQL des systèmes backend robustes qui alimentent les sites web avec efficacité et fiabilité. De plus, j'utilise des plugins comme ACF, WooCommerce, Dokan, et d'autres encore pour améliorer la fonctionnalité et l'expérience utilisateur.",
	"WordPress",
	"J'exploite la flexibilité de WordPress pour créer des sites web dynamiques avec des thèmes et des plugins personnalisés, en mariant le design et la fonctionnalité pour une expérience utilisateur transparente.",
	"Référencement Web",
	"Mes compétences en SEO garantit que votre site web non seulement a une apparence attrayante, mais se classe également bien sur Google! Attirant un trafic organique ciblé grâce à des techniques d'optimisation stratégiques et à l'identification de mots-clés à 'forte intention' les plus efficaces pour vos clients.",
	"Introduire",
	"Bonjour ! Je suis Abdelkarim Achlaih",
	"Tout grand projet de développement commence par une vision claire, une planification méticuleuse et un engagement à transformer les idées en solutions élégantes et fonctionnelles.",
	"Mes deux années d'expérience en tant que développeur web full stack me permettent de concevoir des solutions sur mesure qui répondent aux exigences uniques de votre projet.",
	"Technologies Que J'Utilise",
	"Découvrez les technologies de pointe qui alimentent mon parcours vers l'excellence digitale",

	"Derniers travaux",
	"Des solutions parfaites pour l'expérience digitale",

	"Tous",
	"Projets",
	"Boutiques",
	"Immobilier",
	"Maquettes",

	"Tous les projets",
	"* Parcourir d'autres projets sur ",
	"mon GitHub",
	"Description du Projet",
	"Démonstration en ligne",
	"Voir le code",

	"Processus de Projet",
	"Je vous guide à travers mon processus de projet. De la conception à la livraison, je me suis un chemin stratégique pour garantir que votre vision prenne vie",
	"Je lance le début en plongeant profondément dans vos idées, explorant les possibilités, et posant les bases du succès de votre projet.",
	"Rédaction de contenu",
	"Rédaction de contenu",
	"Avec un accent sur la narration, l'engagement, et l'optimisation SEO, je crée un contenu captivant qui résonne avec votre public, améliore votre récit de marque, et renforce votre visibilité en ligne.",
	"Conception",
	"Conception",
	"Je veille à ce que les éléments visuels que je conçois complètent parfaitement la rédaction de contenu, créant une expérience utilisateur captivante.",
	"Développement",
	"Développement",
	"En utilisant les technologies mentionnées ci-dessus et les meilleures pratiques de l'industrie, je donne vie à vos concepts de design, en créant des sites Web entièrement fonctionnels, riches en fonctionnalités.",
	"Livraison",
	"Livraison",
	"Votre satisfaction est ma priorité. Je livre le produit initial et travaille en étroite collaboration avec vous pour l'améliorer en fonction de vos précieux commentaires.",
	"Développé avec",
	"Performance",
	"Profitez d'une performance élevée avec des sites web conçus pour la vitesse et l'efficacité. Mon engagement envers l'excellence s'étend à l'optimisation de chaque aspect de votre site web, garantissant des temps de chargement ultra-rapides et une expérience utilisateur fluide",
	"Témoignages",
	"Ce que mes clients et amis disent de moi",
	"Nous tenons à vous exprimer notre sincère gratitude pour le travail remarquable que vous avez accompli en développant notre site web officiel à <a target='_blank' href='https://staraimmo.ma'>STARA IMMO</a>. Votre dévouement et votre expertise dans la création de notre présence digitale ont grandement contribué à améliorer notre portée en ligne et à mettre en valeur nos services de manière efficace.",
	"L'un des aspects les plus impressionnants du travail d'Abdelkarim est son engagement à créer des solutions à la fois esthétiques et hautement fonctionnelles.",
	"Ingénieur, Ami",
	"Mes services",
	"Des solutions innovantes qui laissent une impression durable à votre parcours digitale",
	"Optimisation pour les moteurs de recherche (SEO)",
	"Dynamisez votre présence en ligne avec une stratégie SEO sur mesure qui améliore la visibilité de votre site web sur les moteurs de recherche, générant du trafic organique et améliorant les classements. Collaborons pour maximiser votre impact dans le paysage digitale.",
	"Commander",
	"Sites web pour les entreprises",
	"Transformez votre entreprise en une histoire de succès digitale avec des sites web captivants conçus pour séduire votre public et générer des leads. Démystifions les concepts complexes et alignons votre site web sur votre stratégie marketing pour des résultats optimaux.",
	"Commander",
	"Solutions de e-commerce",
	"Élevez votre boutique en ligne à un niveau captivant qui convertit les visiteurs en acheteurs. Collaborons pour optimiser chaque aspect de votre boutique en ligne pour le succès et la fidélisation de la clientèle.",
	"Commander",
	"Sites web personnalisés pour étudiants, blogueurs et artistes",
	"Donnez du poids à votre parcours créatif avec des sites web personnalisés conçus pour mettre en valeur vos talents et vos aspirations. Collaborons pour transformer votre présence digitale en un canevas captivant qui résonne avec votre public.",
	"Commander",
	"PSD ou Figma vers une page web ou un thème WordPress",
	"Donnez vie à vos concepts de design avec précision et élégance. Transformons vos designs créatifs en chefs-d'œuvre digitales interactifs qui captivent votre public.",
	"Commander",
	"Développement d'applications web",
	"Optimisez vos processus commerciaux et améliorez l'expérience utilisateur avec des applications web personnalisées adaptées à vos besoins spécifiques. Révolutionnons votre façon de faire des affaires en ligne avec des solutions intuitives qui stimulent la croissance et l'innovation.",
	"Commander",
	"Réalisons ensemble quelque chose d'extraordinaire.",
	"Commencez par dire bonjour",
	"Nom",
	"Email",
	"Message",
	"2024, Tous droits réservés",
	"Design inspiré de <a href='https://dribbble.com/shots/11276631-DS-Personal-Developer-Portfolio'>Logan Cee</a>",
];
